### ISSUE TITLE
g++ flag

### ISSUE THREAD

**Issue by baoboa** [joe-jordan/pyvoro#1]
in g++ 4.7/4.4.6 (fedora 17 / centos 6.3) flag "-arch x86_64" doesn't work

```
python setup.py build
downloading complicated build...
done!
Compiling pyvoro/voroplusplus.pyx because it changed.
Cythonizing pyvoro/voroplusplus.pyx
g++   -arch x86_64 -I/usr/include/python2.7  -o build/cb_temp/pyvorovoroplusplusx86_64/pyvorovoropluspluscpp.o -c pyvoro/voroplusplus.cpp
g++: error: unrecognized command line option ‘-arch’
g++: error: x86_64: No such file or directory
compiler error detected!
```

removing this flag doesn't help either 

link flag "-bundle -undefined dynamic_lookup" are not recognized

could you precise which OS version you are using for a successful build ?

**Comment by joe-jordan** [comment]
OS = Mac OS X 10.6.8, Snow Leopard

my g++ system info:

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin10/4.7.1/lto-wrapper
Target: x86_64-apple-darwin10
Configured with: ../gcc-4.7.1/configure --prefix=/opt/local --build=x86_64-apple-darwin10 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc47 --includedir=/opt/local/include/gcc47 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-4.7 --with-libiconv-prefix=/opt/local --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.7 --with-gxx-include-dir=/opt/local/include/gcc47/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-ppl=/opt/local --with-cloog=/opt/local --enable-cloog-backend=isl --enable-stage1-checking --disable-multilib --enable-lto --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --disable-ppl-version-check --with-pkgversion='MacPorts gcc47 4.7.1_6'
Thread model: posix
gcc version 4.7.1 (MacPorts gcc47 4.7.1_6) 
```

hmm, sorry about this! do you have another python C extension handy? if you need one, can you try something like [faulthandler](https://github.com/haypo/faulthandler) please.

Run

```
$ python setup.py build
```

in the module and please copy and paste the output here (assuming it builds correctly.) I may need to update `cb` (my own custom build system, alas) to hook into whatever distutils uses to find compiler directives, rather than hard coding what it uses on my Mac!

Please _do_ do the above, to help me resolve the issue, but for now you can run the following commands to use the old setup file (assuming you got the code by `git clone` rather than a tarball download):

```
$ git checkout HEAD~1 .
```

to get pyvoro working for you. (if you did grab a tarball, you can do the same from [this page](https://github.com/joe-jordan/pyvoro/tree/91caa47e44c5c88e6c51932ca8858a682edfe9b4) for the old commit.)

**Comment by baoboa** [comment]
thank for the fast response , i will check on that tomorrow

2013/2/6 Joe Jordan notifications@github.com

**Comment by joe-jordan** [comment]
I have reproduced this on a local debian VM, and am working on a patch for `cb`. In the meantime, please delete the downloaded file called `cb.py` in the project folder, and revert with git as I suggested in the last comment. I'll update this issue when I've fixed `cb`, and then the newer setup.py should work on all/most platforms.

**Comment by baoboa** [comment]
i did follow the step

 git clone https://github.com/joe-jordan/pyvoro.git
 cd pyvoro
 git checkout HEAD~1 .
 python setup.py build
 python setup.py install --user

i did try the example shown in the readme without trouble

so now it's work, thank for your responsiveness

2013/2/7 Joe Jordan notifications@github.com

**Comment by joe-jordan** [comment]
This issue now resolved as of most recent commit.

Required a [commit in complicated_build](https://github.com/joe-jordan/complicated_build/commit/587cc56553e4124143fe728a83136b773d5f89b2) which was rather extensive and should make that build system much more robust for cross-platform work, and a [small tweak](https://github.com/joe-jordan/pyvoro/commit/0f69cd47e33358006e401f535767d65a604ddd28) to this project's setup.py.

Thank you very much, @baoboa, for raising the issue with helpful information and suggestions.
